# Generated by Django 3.0.4 on 2020-03-16 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный ключ')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Название')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата добавления опроса')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала опроса')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания опроса')),
                ('password', models.CharField(default='', max_length=50, verbose_name='Пароль доступа к опросу')),
                ('limit', models.IntegerField(default='0', verbose_name='Ограничение на количество  опрошенных')),
                ('comments', models.NullBooleanField(default=True, verbose_name='Разрешить комментарии')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запось удалена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления вопроса')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Текст вопроса')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок сортировки в опросе')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запось удалена')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pools.Pool')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('pool', 'date_created'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления ответа')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Текст ответа')),
                ('link', models.CharField(default='', max_length=250, verbose_name='Ссылка на вариант ответа')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запось удалена')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pools.Question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('question', 'date_created'),
            },
        ),
    ]
