# Generated by Django 3.0.5 on 2020-04-06 09:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_auto_20200316_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='link',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Ссылка на вариант ответа'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный ключ')),
                ('useragent', models.CharField(blank=True, default='', max_length=250, verbose_name='Агент')),
                ('ipaddress', models.CharField(blank=True, default='', max_length=16, verbose_name='Адрес')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления ответа')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pools.Answer')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'ordering': ('date_created',),
            },
        ),
    ]
