# Generated by Django 3.0.5 on 2020-04-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0003_auto_20200406_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='pools.Question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='pools.Answer'),
        ),
    ]
